### ISSUE TITLE
installer - if upgrade fails - system is left in a fail state

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1032]
due to deleting all files in /usr/local/fworch/*

- [x]  develop ideas how to fix this

Example: upgrade fails if Microsoft packages cannot be downloaded
 - if https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb is not reachable, simply use the old deb  as fallback (does not work for installation_mode=new)

**Comment by alf-cactus** [comment]
Will try to solve with handlers:

Ansible runs handlers at the end of each play. If a task notifies a handler but another task fails later in the play, by default the handler does not run on that host, which may leave the host in an unexpected state. For example, a task could update a configuration file and notify a handler to restart some service. If a task later in the same play fails, the configuration file might be changed but the service will not be restarted.

You can change this behavior with the --force-handlers command-line option, by including force_handlers: True in a play, or by adding force_handlers = True to ansible.cfg. When handlers are forced, Ansible will run all notified handlers on all hosts, even hosts with failed tasks. (Note that certain errors could still prevent the handler from running, such as a host becoming unreachable.)

**Comment by tpurschke** [comment]
done - nice work
