### ISSUE TITLE
upgrade openldap-server

### ISSUE THREAD

**Issue by abarz722** [CactuseSecurity/firewall-orchestrator#1038]
- [x] not sure how to upgrade olcAccess: (in config.ldif.j2)

olcAccess: to dn.children="{{ openldap_std_user_dn }}"
    by dn.base="{{ openldap_writer_dn }}" write
    by dn.base="{{ openldap_superuser_dn }}" write
    by dn.base="{{ openldap_readonly_user_dn }}" read
    by * none
 
should be replaced by 

olcAccess: to dn.subtree="{{ openldap_std_user_dn }}"
    by dn.base="{{ openldap_writer_dn }}" write
    by dn.base="{{ openldap_superuser_dn }}" write
    by dn.base="{{ openldap_readonly_user_dn }}" read
    by * none

How to do it in upgrade file(s)?
dn: olcDatabase=bdb,cn=config
changetype: modify
delete: olcAccess ...
in one file
+ add: olcAccess ...
in another file

or

dn: olcDatabase=bdb,cn=config
changetype: modify
replace: olcAccess
olcAccess: to dn.subtree="{{ openldap_std_user_dn }}"
    by dn.base="{{ openldap_writer_dn }}" write
    by dn.base="{{ openldap_superuser_dn }}" write
    by dn.base="{{ openldap_readonly_user_dn }}" read
    by * none

or do I need to delete/add resp. replace all olcAccess entries of the database?

When trying, I got several times the error "ldap_sasl_interactive_bind_s: Can't contact LDAP server (-1)" and the slapd task on port 389 had disappeared

- [x] upgrade files with subversion are ignored:

TASK [common : debug] ***********************************************************************************************************************************************************************
ok: [fworch-srv] => {
    "msg": [
        "installed_version: 5.2.8",
        "current_version: 5.2.9",
        "all_upgrades_available: /home/achim/firewall-orchestrator/roles/common/tasks/upgrade/5.1.17.yml"
    ]
}
...
TASK [openldap-server : set list of relevant upgrade files (without extension)] *************************************************************************************************************
skipping: [fworch-srv] => (item=/home/achim/firewall-orchestrator/roles/openldap-server/files/../templates/upgrade/5.1.ldif.j2)
skipping: [fworch-srv] => (item=/home/achim/firewall-orchestrator/roles/openldap-server/files/../templates/upgrade/5.2.9.2.ldif.j2)
skipping: [fworch-srv] => (item=/home/achim/firewall-orchestrator/roles/openldap-server/files/../templates/upgrade/5.2.9.1.ldif.j2)

**Comment by alf-cactus** [comment]
The first task is in my fork
