### ISSUE TITLE
auth - security - passwords are only base64 encoded, not hashed

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1059]
when adding a new user via API, the password gets stored in LDAP in plain text (base64 encoded)

**Comment by alf-cactus** [comment]
This is an ui issue. The ansible generated passwords SSHA hashed

**Comment by tpurschke** [comment]
found a link explaining that hashing behaviour should be configurable in openldap server:

source: <https://stackoverflow.com/questions/11731547/how-do-you-turn-on-password-hashing-ssha-in-openldap#11748013>
`When you tried to store userPassword attribute in add/modify LDAP operations, userPassword value is stored as plain text. But you can override this behavior using ppolicy_hash_cleartext option in ppolicy overlay module in OpenLDAP. Once you enable it, when client sends a plain text password, it is stored as SSHA by default. You can find more details on enabling hash password in OpenLADP from here
`
