### ISSUE TITLE
Rename Git

### ISSUE THREAD

**Issue by alf-cactus** [CactuseSecurity/firewall-orchestrator#1061]
- rename master to dev - e.g. https://github.com/MycroftAI/mycroft-core, https://www.hostinger.com/tutorials/how-to-rename-a-git-branch/ and keep it the default branch
- create new main branch for releases
- decide on working on dev branch from now on
- users should get the main branch per default

**Comment by alf-cactus** [comment]
- Rename your local branch.

    git branch -m master main

- Push renamed branch upstream and set remote tracking branch.

    git push -u origin main

- Log into the upstream repository host (GitHub, GitLab, Bitbucket, etc.) and change the "default branch".

- Delete the old branch upstream.

    git push origin --delete master

- Update the upstream remote's HEAD.

    git remote set-head origin -a

That's covers it on your end and where your repository is hosted. Now what do you have to do if it's someone else's repo which renamed a branch, and you're left holding a "dangling" reference (so to speak) to a remote branch that no longer exists?

If you know the branch was renamed, there's nothing to fear. The following steps will get you back on track:

- Fetch the latest branches from the remote.

    git fetch --all

- Update the upstream remote's HEAD.

    git remote set-head origin -a

- Switch your local branch to track the new remote branch.

    git branch --set-upstream-to origin/main

- Rename your branch locally.

    git branch -m master main

That's it! Note that it gets much simpler if you have no remote/upstream. It's just git branch -m master main to rename a branch. The other commands are all concerned about matching local branches to remote ones (via tracking branches) and updating the HEAD reference to point to the "default" branch.

**Comment by tpurschke** [comment]
already moved ahead creating new main and now strictly working against develop branch.

**Comment by alf-cactus** [comment]
Everything works fine
