### ISSUE TITLE
auth - security: Demo users are included in "default" installation

### ISSUE THREAD

**Issue by alf-cactus** [CactuseSecurity/firewall-orchestrator#1080]
If  an installation is started without any flags as described in the git manual, a lot of demo users are created with critical roles (such as auditor)
We could make the installation without demo users new default
@tpurschke What do you think

**Comment by alf-cactus** [comment]
We could tell first time users at the initial page, that unsecure demo users are present on the system

**Comment by tpurschke** [comment]
fixed in v5.3.2
