### ISSUE TITLE
ldap settings - re-design api architecture

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1089]
was: adding ldap server not using mw server
existing roles/middleware/files/FWO.Middleware.Server/Requests/AddLdapRequestHandler.cs is not used but UI  adds LDAP directly (in roles/ui/files/FWO_UI/Pages/Settings/SettingsLdap.razor).

idea was: all auth relevant communication should go thru mw server 

@abarz722 was this done intentionally?

**Comment by abarz722** [comment]
Currently only requests to the Ldap content go through the mw server. The access to the Db tables (ldap_connection as well as all other tables) is done directly via api. mw server is also listening for some some unused schedule requests (AddReportSchedule, EditReportSchedule, DeleteReportSchedule).
We should define if and which parts (tables/columns) of the db should only be accessed by mw server.

**Comment by tpurschke** [comment]
completed and documented in drawio
