### ISSUE TITLE
Database: Failed installation due to permission error on tmp files

### ISSUE THREAD

**Issue by alf-cactus** [CactuseSecurity/firewall-orchestrator#1149]
**Bug report**
TASK [database : check if database already exists] *****************************
fatal: [fworch-srv]: FAILED! => 
  msg: |-
    Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/var/tmp/ansible-tmp-1630576349.767145-35948006218567/': Operation not permitted
    chown: changing ownership of '/var/tmp/ansible-tmp-1630576349.767145-35948006218567/AnsiballZ_postgresql_query.py': Operation not permitted
    }). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user

**To Reproduce**
Ubuntu 20.04 Server: normal installation without

    allow_world_readable_tmpfiles = True

or

    pipelining = True

in ansible.cfg

**Comment by tpurschke** [comment]
leaving config as:
[ssh_connection]
pipelining = True
