### ISSUE TITLE
db upgrade 5.4.1 failing in second attempt

### ISSUE THREAD

**Issue by abarz722** [CactuseSecurity/firewall-orchestrator#1172]
The second attempt of upgrade db to 5.4.1 is failing (first attempt had failed at a later stage because of temporary debian upgrade issue, so first db upgrade most likely was already Ok):

TASK [database : install upgrades normally] *************************************************************************************************************************************************
failed: [fworch-srv] (item=5.4.1) => changed=false
  ansible_loop_var: item
  item: 5.4.1
  msg: |-
    Cannot execute SQL '
    -- Grant ALL on "import_service" to group "configimporters";
...
CREATE TRIGGER import_config_insert
        BEFORE INSERT ON import_config
        FOR EACH ROW
        EXECUTE PROCEDURE import_config_from_jsonb ();
    ' None: relation "import_full_config" already exists

**Comment by tpurschke** [comment]
found this one in roles/database/files/upgrade/5.4.1.sql:
CREATE TABLE "import_full_config" (
 --> 
CREATE TABLE IF NOT EXISTS "import_full_config" (
