### ISSUE TITLE
API / UI - set correct role in request header

### ISSUE THREAD

**Issue by abarz722** [CactuseSecurity/firewall-orchestrator#1303]
- test setting of current role per page
- needed by #55 
- check and maybe fix the prioritization and handling of different roles of the same user.
- Maybe new JWTs have to be created when acting in different roles.
- x-hasura-role has to be sent with the http request. It is not expected to be part of the JWT's hasura claims and as such it is ignored. The x-hasura-role sent with the request is checked to see if it is part of the x-hasura-allowed-roles and if yes, the request is executed as that role. In case the x-hasura-role is missing, the x-hasura-default-role from the JWT is used. (source: https://github.com/hasura/graphql-engine/issues/2849)
- which means that e. g. within reporting menu a we need to
  - option 1: assign reporter-viewall role to an auditor to enable him/her to do reporting properly
  - option 2: set permissions of role auditor so that reporting is possible (contains all permissions from reporter-viewall role)
  for option 1 we would need to  set a  "x-hasura-role" header to either reporter or reporter-viewall  depending on the user's rights. for option 2 we could work with a signle role - but would need to handle additional (unnecessary) roles.
- another approach might be working with inherited roles: https://hasura.io/docs/latest/graphql/core/auth/authorization/inherited-roles.html, defining pwd-changer-role, demo-user = "read-only-user",  auditor = "read-only-user + pwd-changer" (need to first set HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: "inherited_roles") and making sure that each user has exactly one role assigned

**Comment by tpurschke** [comment]
@abarz722 does the above help with role handling within C#?
