### ISSUE TITLE
Middleware requests unauthorized after refresh in browser

### ISSUE THREAD

**Issue by abarz722** [CactuseSecurity/firewall-orchestrator#1355]
After a refresh in browser (Chrome or FF): Call of the middlewareClient lead to HttpStatusCode "Unauthorized"

Reproduce: Login -> reload any page in UI -> go to e.g. User settings -> Error Message like "Fetch Roles - No roles found . See log for details!"
Logout + Login again -> everything works again

**Comment by tpurschke** [comment]
- cannot reproduce 
- after reload I can still generate reports, etc. no error message
- tested with latest develop version https://github.com/CactuseSecurity/firewall-orchestrator/commit/022cc6ed473a5b7b1dfed37bb0117c256f290bb5 with chromium & FF

**Comment by abarz722** [comment]
Error occurs only in user settings, where Middleware server is called via RestAPI: Ldap, tenant, user, group, role.
Also occurs on Demo-Server (here only for user, group and role settings, as the rest is not on REST)

**Comment by tpurschke** [comment]
@NilsPur can you have a look at the rest API behaviour when reloading the session?

**Comment by tpurschke** [comment]
reload tested: was fixed in #1357
