### ISSUE TITLE
Ldap User are still existing after deleting them in GUI

### ISSUE THREAD

**Issue by alf-cactus** [CactuseSecurity/firewall-orchestrator#1390]
After removing demo user and tenants in GUI they still exist in Ldap. To recreate use the command

    sudo ldapsearch -H ldaps://127.0.0.1 -D cn=Manager,ou=systemuser,ou=user,dc=fworch,dc=internal -y /usr/local/fworch/etc/secrets/ldap_manager_pw.txt -x | grep demo

**Comment by abarz722** [comment]
users, groups could be deleted in ldap, but there was a bug in tenant deletion
