### ISSUE TITLE
encrypt passwords and keys

### ISSUE THREAD

**Issue by abarz722** [CactuseSecurity/firewall-orchestrator#1508]
goal: database must not contain any cleartext passwords (currently mainly fw management api passwords for importing)

- [x] put the encryption key (mainkey) into file in etc/secrets
- [x] to keep it idempotent, upgrade script must first check if a key is already encrypted by trying to decrypt
- [x] all reads to passwords (both in importer and C# parts) must read the mainkey and decrypt the passwords with it, then resume as before
- [x] all pwd writes must add salt and enrypt before writing passwords/keys
- [x] encrypt ldap_connections.ldap_search_user_pwd
- [x] decrypt pwd in importer
- [x] decrypt pwd in autodiscovery (mw)

**Comment by tpurschke** [comment]
needed for compliance reasons
