### ISSUE TITLE
research: ansible error message ansible_fact_cache permissions

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1553]
could the following have any negative impact? It occurs on a prod customer system. 

[WARNING]: error in 'jsonfile' cache, configured path (/tmp/ansible_fact_cache) does not have necessary permissions (rwx), disabling plugin

**Comment by alf-cactus** [comment]
From Ansible:

    Cache plugins allow Ansible to store gathered facts or inventory source data without the performance hit of retrieving them from source.

A disabled cache plugin decreases performance. On my local testmachine I find

    $ ll /tmp
    drwxrwxr-x  2 alf  alf  4096 Mar 14 11:16 ansible_fact_cache/

My best idea for a fix is to enhance user permission of /tmp/ansible_fact_cache/ to rwx

**Comment by tpurschke** [comment]
ok, thanks, but for security reasons I would really not like to do this.
