### ISSUE TITLE
settings - pwd policy - UI freeze with latest version 

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1559]
- with the latest version the UI freezes when navigating to password policy
- seems to be an issue that with inverted behaviour on your end @abarz722 ?
- related to task change from last PR?

**Comment by abarz722** [comment]
@tpurschke are you sure, that you have the latest version? Because this is the behavior I had before my last PR (for all settings where configs are initially read: password policy, report, default)

**Comment by tpurschke** [comment]
your are completely right - after upgrade to latest version - everything works fine
