### ISSUE TITLE
installer: catch errors in all command and shell tasks

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#160]
Final list of commands:
apache_create_server_cert.sh
a2ensite
{{ api_hasura_cli_bin }}
dotnet
ldapmodify
ldapsearch
slappasswd
slapadd

Final list of shells:
create api documentation using 2fd/graphdoc -> new issue

roles to do:
- [x] api
```
no ansible build in commands for hasura
shell script apache_create_server_cert.sh is still executed
no ansible module for enabling apache2 sites
```
- [x] common
- [x] database
- [x] docker
- [x] frontend-php
- [x] importer
- [x] lib
- [x] middleware
```
we need command: ldapmodify
one issue: The goal is to replace debian specific commands. For now this is a collection
1. In auth_install_dot_net.yml
    name: install ms package list
    command: "dpkg -i {{ auth_server_base_dir }}/{{ dotnet_deb_name }}"

2. In ui_install_dot_net.yml
    name: install ms package list
    command: "dpkg -i {{ ui_dir }}/{{ dotnet_deb_name }}"
```
- [x] openldap-server - single     shell: "slappasswd -T {{ fworch_home }}/etc/secrets/ldap_manager_pw.txt"
- [x] sample-auth-data
```
we need command: ldapmodify
```
- [x] sample-data
```
we need command: ldapmodify
```
- [x] sample-data-connect-sting
- [x] test
- [x] ui roles/ui/tasks/ui_apache_install_and_setup.yml
       "dotnet publish -c {{ dotnet_mode }}" --> add error handling
```    - name: enable {{ product_name }} web site
      command: "a2ensite {{ product_name }}-ui"
      register: testoutput

    - name: test
      debug:
        var: testoutput
```
 --> there currently is no ansible module for enabling apache2 sites (not modules), so we need to use command and add error handling
- [x] upgrade-completion
- [x] webhook

**Comment by alf-cactus** [comment]
From Ansible Documentation:
**Error handling in playbooks**
When Ansible receives a non-zero return code from a command or a failure from a module, by default it stops executing on that host and continues on other hosts.

This means, that we have to decide for the remaining commands whether non-zero return codes should be treated as succes
