### ISSUE TITLE
installer - support for Ubuntu 22.04 missing in PDF generator

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1680]
- [x] unify pipelining and install with "sudo"
- [x] PDF Gen error
```
  Failed GeneratePdf [30 ms]
      Error Message:
       System.AggregateException : One or more errors occurred. (Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.)
```

- [x] fix error with slapd; error produced with

  - desktop version (ansible 2.10.8)
  - tim@fworch-comp:~/firewall-orchestrator-tpur$ slapd -V

       @(#) $OpenLDAP: slapd 2.5.11+dfsg-1~exp1ubuntu3 (Feb 16 2022 17:15:26) $
```
TASK [openldap-server : Initialize ldap config] **************************************************************************************************
fatal: [fworch-srv]: FAILED! => changed=true 
  cmd:
  - slapadd
  - -F
  - /etc/ldap/slapd.d
  - -n
  - '0'
  - -l
  - /etc/ldap/slapd.d/config.ldif
  delta: '0:00:00.008946'
  end: '2022-04-22 10:10:33.691683'
  msg: non-zero return code
  rc: 1
  start: '2022-04-22 10:10:33.682737'
  stderr: |-
    lt_dlopenext failed: (back_bdb.la) file not found
    slapadd: could not add entry dn="cn=module{0},cn=config" (line=11): <olcModuleLoad> handler exited with 1
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

```

might need to add config /etc/ldap/ldap.conf

    # Load dynamic backend modules:
    # modulepath xxx
    moduleload back_bdb.la

**Comment by alf-cactus** [comment]
I hope to resolve this issue with PR #1684

We have a c# testing issue, I attach the error output

**Comment by alf-cactus** [comment]
TASK [test : csharp tests] ********************************************************
fatal: [fworch-srv]: FAILED! => changed=true 
  cmd:
  - dotnet
  - test
  delta: '0:00:19.083354'
  end: '2022-04-25 13:23:14.004856'
  msg: non-zero return code
  rc: 1
  start: '2022-04-25 13:22:54.921502'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |2-
      Determining projects to restore...
      Restored /usr/local/fworch/test/csharp/FWO.Test/FWO.Test.csproj (in 9.45 sec).
      8 of 9 projects are up-to-date for restore.
      FWO.Logging -> /usr/local/fworch/lib/files/FWO.Logging/bin/Debug/net6.0/FWO.Logging.dll
      FWO.Config.File -> /usr/local/fworch/lib/files/FWO.Config.File/bin/Debug/net6.0/FWO.Config.File.dll
      FWO.Middleware -> /usr/local/fworch/lib/files/FWO.Middleware/bin/Debug/net6.0/FWO.Middleware.dll
    /usr/local/fworch/lib/files/FWO.Api.Client/ApiSubscription.cs(31,21): warning CS0162: Unreachable code detected [/usr/local/fworch/lib/files/FWO.Api.Client/FWO.Api.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Api.Client/APIConnection.cs(105,25): warning CS0162: Unreachable code detected [/usr/local/fworch/lib/files/FWO.Api.Client/FWO.Api.Client.csproj]
      FWO.Api.Client -> /usr/local/fworch/lib/files/FWO.Api.Client/bin/Debug/net6.0/FWO.Api.Client.dll
      FWO.Middleware.Client -> /usr/local/fworch/lib/files/FWO.Middleware.Client/bin/Debug/net6.0/FWO.Middleware.Client.dll
    /usr/local/fworch/lib/files/FWO.Config.Api/UserConfig.cs(43,16): warning CS8618: Non-nullable property 'User' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/usr/local/fworch/lib/files/FWO.Config.Api/FWO.Config.Api.csproj]
    /usr/local/fworch/lib/files/FWO.Config.Api/UserConfig.cs(84,34): warning CS8625: Cannot convert null literal to non-nullable reference type. [/usr/local/fworch/lib/files/FWO.Config.Api/FWO.Config.Api.csproj]
    /usr/local/fworch/lib/files/FWO.Config.Api/Config.cs(30,19): warning CS8618: Non-nullable field 'apiConnection' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/usr/local/fworch/lib/files/FWO.Config.Api/FWO.Config.Api.csproj]
    /usr/local/fworch/lib/files/FWO.Config.Api/Config.cs(32,19): warning CS8618: Non-nullable field 'apiConnection' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/usr/local/fworch/lib/files/FWO.Config.Api/FWO.Config.Api.csproj]
      FWO.Config.Api -> /usr/local/fworch/lib/files/FWO.Config.Api/bin/Debug/net6.0/FWO.Config.Api.dll
    /usr/local/fworch/lib/files/FWO.Report.Filter/Ast/AstNodeFilterDateTimeRange.cs(11,23): warning CS8618: Non-nullable field 'semanticValue' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/usr/local/fworch/lib/files/FWO.Report.Filter/FWO.Report.Filter.csproj]
      FWO.Report.Filter -> /usr/local/fworch/lib/files/FWO.Report.Filter/bin/Debug/net6.0/FWO.Report.Filter.dll
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/CheckPointAPI.cs(204,29): warning CS8618: Non-nullable property 'DomainList' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryFortiManager.cs(63,57): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryFortiManager.cs(96,67): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryFortiManager.cs(142,82): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryFortiManager.cs(143,25): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/CheckPointAPI.cs(97,38): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/CheckPointAPI.cs(117,47): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
      FWO.DeviceAutoDiscovery -> /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/bin/Debug/net6.0/FWO.DeviceAutoDiscovery.dll
    /usr/local/fworch/test/csharp/FWO.Test/ApiTest.cs(19,16): warning CS8618: Non-nullable field 'apiConnection' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/usr/local/fworch/test/csharp/FWO.Test/FWO.Test.csproj]
    /usr/local/fworch/test/csharp/FWO.Test/ApiTest.cs(51,27): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/usr/local/fworch/test/csharp/FWO.Test/FWO.Test.csproj]
    /usr/local/fworch/test/csharp/FWO.Test/ApiTest.cs(17,23): warning CS0169: The field 'ApiTest.apiConnection' is never used [/usr/local/fworch/test/csharp/FWO.Test/FWO.Test.csproj]
      FWO.Test -> /usr/local/fworch/test/csharp/FWO.Test/bin/Debug/net6.0/FWO.Test.dll
    Test run for /usr/local/fworch/test/csharp/FWO.Test/bin/Debug/net6.0/FWO.Test.dll (.NETCoreApp,Version=v6.0)
    Microsoft (R) Test Execution Command Line Tool Version 17.1.0
    Copyright (c) Microsoft Corporation.  All rights reserved.
  
    Starting test execution, please wait...
    A total of 1 test files matched the specified pattern.
    2022-04-25T13:23:13+00:00 Info - Test Log (HtmlToPdfTest.cs in line 31), starting PDF generation
  
      Failed GeneratePdf [30 ms]
      Error Message:
       System.AggregateException : One or more errors occurred. (Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.)
      ----> System.NotSupportedException : Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.
      Stack Trace:
         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Threading.Tasks.Task.Wait()
       at WkHtmlToPdfDotNet.SynchronizedConverter.Invoke[TResult](Func`1 delegate)
       at WkHtmlToPdfDotNet.SynchronizedConverter.Convert(IDocument document)
       at FWO.Test.HtmlToPdf.HtmlToPdfTest.GeneratePdf() in /usr/local/fworch/test/csharp/FWO.Test/HtmlToPdfTest.cs:line 57
    --NotSupportedException
       at WkHtmlToPdfDotNet.ModuleFactory.GetModule()
       at WkHtmlToPdfDotNet.PdfTools.Load()
       at WkHtmlToPdfDotNet.BasicConverter.Convert(IDocument document)
       at WkHtmlToPdfDotNet.SynchronizedConverter.<>n__0(IDocument document)
       at WkHtmlToPdfDotNet.SynchronizedConverter.<>c__DisplayClass4_0.<Convert>b__0()
       at System.Threading.Tasks.Task`1.InnerInvoke()
       at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location ---
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      Standard Output Messages:
     2022-04-25T13:23:13+00:00 Info - Test Log (HtmlToPdfTest.cs in line 31), starting PDF generation
  
  
  
    Failed!  - Failed:     1, Passed:    10, Skipped:     0, Total:    11, Duration: 169 ms - /usr/local/fworch/test/csharp/FWO.Test/bin/Debug/net6.0/FWO.Test.dll (net6.0)
  stdout_lines: <omitted>

**Comment by alf-cactus** [comment]
`TASK [test : csharp tests] ********************************************************
fatal: [fworch-srv]: FAILED! => changed=true 
  cmd:
  - dotnet
  - test
  delta: '0:00:19.083354'
  end: '2022-04-25 13:23:14.004856'
  msg: non-zero return code
  rc: 1
  start: '2022-04-25 13:22:54.921502'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |2-
      Determining projects to restore...
      Restored /usr/local/fworch/test/csharp/FWO.Test/FWO.Test.csproj (in 9.45 sec).
      8 of 9 projects are up-to-date for restore.
      FWO.Logging -> /usr/local/fworch/lib/files/FWO.Logging/bin/Debug/net6.0/FWO.Logging.dll
      FWO.Config.File -> /usr/local/fworch/lib/files/FWO.Config.File/bin/Debug/net6.0/FWO.Config.File.dll
      FWO.Middleware -> /usr/local/fworch/lib/files/FWO.Middleware/bin/Debug/net6.0/FWO.Middleware.dll
    /usr/local/fworch/lib/files/FWO.Api.Client/ApiSubscription.cs(31,21): warning CS0162: Unreachable code detected [/usr/local/fworch/lib/files/FWO.Api.Client/FWO.Api.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Api.Client/APIConnection.cs(105,25): warning CS0162: Unreachable code detected [/usr/local/fworch/lib/files/FWO.Api.Client/FWO.Api.Client.csproj]
      FWO.Api.Client -> /usr/local/fworch/lib/files/FWO.Api.Client/bin/Debug/net6.0/FWO.Api.Client.dll
      FWO.Middleware.Client -> /usr/local/fworch/lib/files/FWO.Middleware.Client/bin/Debug/net6.0/FWO.Middleware.Client.dll
    /usr/local/fworch/lib/files/FWO.Config.Api/UserConfig.cs(43,16): warning CS8618: Non-nullable property 'User' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/usr/local/fworch/lib/files/FWO.Config.Api/FWO.Config.Api.csproj]
    /usr/local/fworch/lib/files/FWO.Config.Api/UserConfig.cs(84,34): warning CS8625: Cannot convert null literal to non-nullable reference type. [/usr/local/fworch/lib/files/FWO.Config.Api/FWO.Config.Api.csproj]
    /usr/local/fworch/lib/files/FWO.Config.Api/Config.cs(30,19): warning CS8618: Non-nullable field 'apiConnection' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/usr/local/fworch/lib/files/FWO.Config.Api/FWO.Config.Api.csproj]
    /usr/local/fworch/lib/files/FWO.Config.Api/Config.cs(32,19): warning CS8618: Non-nullable field 'apiConnection' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/usr/local/fworch/lib/files/FWO.Config.Api/FWO.Config.Api.csproj]
      FWO.Config.Api -> /usr/local/fworch/lib/files/FWO.Config.Api/bin/Debug/net6.0/FWO.Config.Api.dll
    /usr/local/fworch/lib/files/FWO.Report.Filter/Ast/AstNodeFilterDateTimeRange.cs(11,23): warning CS8618: Non-nullable field 'semanticValue' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/usr/local/fworch/lib/files/FWO.Report.Filter/FWO.Report.Filter.csproj]
      FWO.Report.Filter -> /usr/local/fworch/lib/files/FWO.Report.Filter/bin/Debug/net6.0/FWO.Report.Filter.dll
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/CheckPointAPI.cs(204,29): warning CS8618: Non-nullable property 'DomainList' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryFortiManager.cs(63,57): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryFortiManager.cs(96,67): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryFortiManager.cs(142,82): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryFortiManager.cs(143,25): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/CheckPointAPI.cs(97,38): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/CheckPointAPI.cs(117,47): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
      FWO.DeviceAutoDiscovery -> /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/bin/Debug/net6.0/FWO.DeviceAutoDiscovery.dll
    /usr/local/fworch/test/csharp/FWO.Test/ApiTest.cs(19,16): warning CS8618: Non-nullable field 'apiConnection' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/usr/local/fworch/test/csharp/FWO.Test/FWO.Test.csproj]
    /usr/local/fworch/test/csharp/FWO.Test/ApiTest.cs(51,27): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/usr/local/fworch/test/csharp/FWO.Test/FWO.Test.csproj]
    /usr/local/fworch/test/csharp/FWO.Test/ApiTest.cs(17,23): warning CS0169: The field 'ApiTest.apiConnection' is never used [/usr/local/fworch/test/csharp/FWO.Test/FWO.Test.csproj]
      FWO.Test -> /usr/local/fworch/test/csharp/FWO.Test/bin/Debug/net6.0/FWO.Test.dll
    Test run for /usr/local/fworch/test/csharp/FWO.Test/bin/Debug/net6.0/FWO.Test.dll (.NETCoreApp,Version=v6.0)
    Microsoft (R) Test Execution Command Line Tool Version 17.1.0
    Copyright (c) Microsoft Corporation.  All rights reserved.
  
    Starting test execution, please wait...
    A total of 1 test files matched the specified pattern.
    2022-04-25T13:23:13+00:00 Info - Test Log (HtmlToPdfTest.cs in line 31), starting PDF generation
  
      Failed GeneratePdf [30 ms]
      Error Message:
       System.AggregateException : One or more errors occurred. (Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.)
      ----> System.NotSupportedException : Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.
      Stack Trace:
         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Threading.Tasks.Task.Wait()
       at WkHtmlToPdfDotNet.SynchronizedConverter.Invoke[TResult](Func`1 delegate)
       at WkHtmlToPdfDotNet.SynchronizedConverter.Convert(IDocument document)
       at FWO.Test.HtmlToPdf.HtmlToPdfTest.GeneratePdf() in /usr/local/fworch/test/csharp/FWO.Test/HtmlToPdfTest.cs:line 57
    --NotSupportedException
       at WkHtmlToPdfDotNet.ModuleFactory.GetModule()
       at WkHtmlToPdfDotNet.PdfTools.Load()
       at WkHtmlToPdfDotNet.BasicConverter.Convert(IDocument document)
       at WkHtmlToPdfDotNet.SynchronizedConverter.<>n__0(IDocument document)
       at WkHtmlToPdfDotNet.SynchronizedConverter.<>c__DisplayClass4_0.<Convert>b__0()
       at System.Threading.Tasks.Task`1.InnerInvoke()
       at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location ---
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      Standard Output Messages:
     2022-04-25T13:23:13+00:00 Info - Test Log (HtmlToPdfTest.cs in line 31), starting PDF generation
  
  
  
    Failed!  - Failed:     1, Passed:    10, Skipped:     0, Total:    11, Duration: 169 ms - /usr/local/fworch/test/csharp/FWO.Test/bin/Debug/net6.0/FWO.Test.dll (net6.0)
  stdout_lines: <omitted>`

**Comment by tpurschke** [comment]
```
  Failed GeneratePdf [30 ms]
      Error Message:
       System.AggregateException : One or more errors occurred. (Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.)
```

**Comment by tpurschke** [comment]
created https://github.com/HakanL/WkHtmlToPdf-DotNet/issues/80 for this

**Comment by tpurschke** [comment]
library files seem to be generate fine on ubu22 (looks identical to e.g. deb10):

```
tim@fwo-ubu22-desktop:/usr/local/fworch$ find . -name "*.so"
./ui/files/FWO.UI/bin/Release/net6.0/runtimes/linux-x86/native/libwkhtmltox.so
./ui/files/FWO.UI/bin/Release/net6.0/runtimes/linux-x64/native/libwkhtmltox.so
./ui/files/FWO.UI/bin/Release/net6.0/runtimes/linux-arm64/native/libwkhtmltox.so
./middleware/files/FWO.Middleware.Server/bin/Release/net6.0/runtimes/linux-x86/native/libwkhtmltox.so
./middleware/files/FWO.Middleware.Server/bin/Release/net6.0/runtimes/linux-x64/native/libwkhtmltox.so
./middleware/files/FWO.Middleware.Server/bin/Release/net6.0/runtimes/linux-arm64/native/libwkhtmltox.so
./.nuget/packages/runtime.ubuntu.16.10-x64.runtime.native.system.security.cryptography.openssl/4.3.0/runtimes/ubuntu.16.10-x64/native/System.Security.Cryptography.Native.OpenSsl.so
./.nuget/packages/runtime.rhel.7-x64.runtime.native.system.security.cryptography.openssl/4.3.0/runtimes/rhel.7-x64/native/System.Security.Cryptography.Native.OpenSsl.so
./.nuget/packages/runtime.debian.8-x64.runtime.native.system.security.cryptography.openssl/4.3.0/runtimes/debian.8-x64/native/System.Security.Cryptography.Native.OpenSsl.so
./.nuget/packages/runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl/4.3.0/runtimes/opensuse.13.2-x64/native/System.Security.Cryptography.Native.OpenSsl.so
./.nuget/packages/haukcode.wkhtmltopdfdotnet/1.5.82/runtimes/linux-x86/native/libwkhtmltox.so
./.nuget/packages/haukcode.wkhtmltopdfdotnet/1.5.82/runtimes/linux-x64/native/libwkhtmltox.so
./.nuget/packages/haukcode.wkhtmltopdfdotnet/1.5.82/runtimes/linux-arm64/native/libwkhtmltox.so
./.nuget/packages/runtime.fedora.23-x64.runtime.native.system.security.cryptography.openssl/4.3.0/runtimes/fedora.23-x64/native/System.Security.Cryptography.Native.OpenSsl.so
./.nuget/packages/microsoft.codecoverage/17.2.0/build/netstandard1.0/InstrumentationEngine/ubuntu/x64/libCoverageInstrumentationMethod.so
./.nuget/packages/microsoft.codecoverage/17.2.0/build/netstandard1.0/InstrumentationEngine/ubuntu/x64/libInstrumentationEngine.so
./.nuget/packages/microsoft.codecoverage/17.2.0/build/netstandard1.0/InstrumentationEngine/alpine/x64/libCoverageInstrumentationMethod.so
./.nuget/packages/microsoft.codecoverage/17.2.0/build/netstandard1.0/InstrumentationEngine/alpine/x64/libInstrumentationEngine.so
./.nuget/packages/runtime.opensuse.42.1-x64.runtime.native.system.security.cryptography.openssl/4.3.0/runtimes/opensuse.42.1-x64/native/System.Security.Cryptography.Native.OpenSsl.so
./.nuget/packages/runtime.ubuntu.14.04-x64.runtime.native.system.security.cryptography.openssl/4.3.0/runtimes/ubuntu.14.04-x64/native/System.Security.Cryptography.Native.OpenSsl.so
./.nuget/packages/runtime.ubuntu.16.04-x64.runtime.native.system.security.cryptography.openssl/4.3.0/runtimes/ubuntu.16.04-x64/native/System.Security.Cryptography.Native.OpenSsl.so
./.nuget/packages/runtime.fedora.24-x64.runtime.native.system.security.cryptography.openssl/4.3.0/runtimes/fedora.24-x64/native/System.Security.Cryptography.Native.OpenSsl.so
./test/csharp/FWO.Test/bin/Debug/net6.0/runtimes/linux-x86/native/libwkhtmltox.so
./test/csharp/FWO.Test/bin/Debug/net6.0/runtimes/linux-x64/native/libwkhtmltox.so
./test/csharp/FWO.Test/bin/Debug/net6.0/runtimes/linux-arm64/native/libwkhtmltox.so
find: ‘./.ssh’: Keine Berechtigung
find: ‘./etc/secrets’: Keine Berechtigung
tim@fwo-ubu22-desktop:/usr/local/fworch$ 

```

**Comment by tpurschke** [comment]
By downloading and running pre-compiled version from https://wkhtmltopdf.org/downloads.html found the missing dependency:
```
tim@fwo-ubu22-desktop:~$ sudo dpkg -i wkhtmltox_0.12.6.1-2.jammy_amd64.deb 
Vormals nicht ausgewähltes Paket wkhtmltox wird gewählt.
(Lese Datenbank ... 235642 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von wkhtmltox_0.12.6.1-2.jammy_amd64.deb ...
Entpacken von wkhtmltox (1:0.12.6.1-2.jammy) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von wkhtmltox:
 wkhtmltox hängt ab von xfonts-75dpi; aber:
  Paket xfonts-75dpi ist nicht installiert.

dpkg: Fehler beim Bearbeiten des Paketes wkhtmltox (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Trigger für man-db (2.10.2-1) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 wkhtmltox
tim@fwo-ubu22-desktop:~$ sudo apt install xfonts-75dpi
```

**Comment by tpurschke** [comment]
standard clean installation with ubuntu 22.04 server fails to install libssl1.1
