### ISSUE TITLE
Show several user messages

### ISSUE THREAD

**Issue by abarz722** [CactuseSecurity/firewall-orchestrator#1698]
currently only one message can be displayed. But there may be several messages in the same transaction. Maybe a maximum of 3 could be appropriate (or even more sophisticated: a new settings value defining the maximum)

**Comment by tpurschke** [comment]
@SolidProgramming this might also be a good issue for you later (but low prio)

**Comment by SolidProgramming** [comment]
> @SolidProgramming this might also be a good issue for you later (but low prio)

Message like the alert messages or the message like the one from the login form?

**Comment by tpurschke** [comment]
This ist about the Standard (Error/Userinfo) Messages displayed in the UI

**Comment by SolidProgramming** [comment]
Alright. Shouldn't be much of a problem.

**Comment by SolidProgramming** [comment]
@tpurschke Closed as it's merged
