### ISSUE TITLE
Installer Ubuntu 20.04

### ISSUE THREAD

**Issue by NilsPur** [CactuseSecurity/firewall-orchestrator#1699]
failed: [fworch-srv] (item=libpq-dev) => changed=false 
  ansible_loop_var: item
  cache_update_time: 1651570287
  cache_updated: false
  item: libpq-dev
  msg: |-
    '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"      install 'libpq-dev'' failed: E: Unable to correct problems, you have held broken packages.
  rc: 100
  stderr: |-
    E: Unable to correct problems, you have held broken packages.
  stderr_lines: <omitted>
  stdout: |-
    Reading package lists...
    Building dependency tree...
    Reading state information...
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
  
    The following packages have unmet dependencies:
     libpq-dev : Depends: libpq5 (= 12.9-0ubuntu0.20.04.1) but 14.2-1.pgdg20.04+1+b1 is to be installed
  stdout_lines: <omitted>

**Comment by tpurschke** [comment]
only occurs when pgadmin4 source are included in apt on target system - closing as rare case
