### ISSUE TITLE
Filter Criteria Syntax Error "DestinationPort " incomprehensible

### ISSUE THREAD

**Issue by dos-box** [CactuseSecurity/firewall-orchestrator#1728]
**Describe the bug**
The error message contains the expected DestinationPort token, but using this token reports an error

**Comment by dos-box** [comment]
![Bildschirmfoto vom 2022-06-10 16-02-25](https://user-images.githubusercontent.com/65412839/173082845-0241ad35-ac8a-4be1-a210-db6c8e31ecef.png)

**Comment by NilsPur** [comment]
The destination port filter can currently be used with one of the following syntaxes:  "destinationport", "port", "dport", "dst_port", "dst-port", "dest-port", "destination-port", "dest_port", "destination_port". However, I have now also added "DestinationPort" 😃 and all other token types as valid syntax. Important: The error itself refers only to the token type, not to the syntactic level (Expected token of type: ...).

**Comment by tpurschke** [comment]
fixed in #1729
