### ISSUE TITLE
UI: login with importer role freezes login page

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1732]
login to UI with importer user hangs 
message: Maybe backend (API or database) is unreachable. Please contact administrator
can we catch this before error occurs?
should ideally just return "Invalid credentials" (same as with wrong password

**Comment by NilsPur** [comment]
Importer role misses db user table access => Leads to failing on login trying to fetch user infos

**Comment by tpurschke** [comment]
fixed
