### ISSUE TITLE
database - materialized view view_tenant_rules empty after clean install

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1750]
directly after clean install, the view is empty:
```
fworchdb=# select count(*) from view_tenant_rules ;
 count 
-------
     0
(1 row)
```
this helps:
```
fworchdb=# REFRESH MATERIALIZED VIEW view_tenant_rules;
REFRESH MATERIALIZED VIEW
fworchdb=# select count(*) from view_tenant_rules ;
 count 
-------
   217
(1 row)

fworchdb=#
``` 

but not when executed in installer script?! Might be due to the fact that the underlying rule table is still empty at that time.
This would mean that the materialized view is a very static table and needs to be refreshed manually every time before accessing it? This would render it useless for our purposes or we would have to trigger a refresh whenever there is a change to the rule table. @Y4nnikH can you test this hypothesis?

**Comment by Y4nnikH** [comment]
https://stackoverflow.com/questions/23906977/refresh-a-materialized-view-automatically-using-a-rule-or-notify#23963969

**Comment by tpurschke** [comment]
works as designed, may use triggers to circumvent it
