### ISSUE TITLE
fatal: [fworch-srv]: failed! => changed=false

### ISSUE THREAD

**Issue by kamranrafiq** [CactuseSecurity/firewall-orchestrator#1830]
When the installation was finished, at the end got the below error and UI is not loading up.

fatal: [fworch-srv]: failed! => changed=false
found existing installation but running with installation_mode set to new. if you want to upgrade, use 'installation_mode=upgrade'.

**Comment by alf-cactus** [comment]
This output suggests that you installed FWO and then tried to install it again. This is checked by the existence of the central config file /usr/local/fworch/etc/fworch.json

If you really want to make a new installation you can either
1. Reinstall via

    sudo ansible-playbook -e "installation_mode=uninstall" site.yml -K
    sudo ansible-playbook -e "installation_mode=new" site.yml -K

2. Reset your machine to the state before the installation. This is useful if you work on a virtual machine and have a snapshot from before you started the initial installation

**Comment by kamranrafiq** [comment]
Thank you @alf-cactus This worked.

**Comment by kamranrafiq** [comment]
However what's the credentials i need to use to login? While installation it does not provide any login username/password.

**Comment by alf-cactus** [comment]
If you complete the initial installation the last ansible play should return

"Your initial UI admin password is '{{ admin_password }}'"
"Your api hasura admin secret is '{{ api_hasura_admin_secret }}'"

These passwords are created randomly during installation unless you set the -e "testkeys=yes" flag for installation.

The inital ui password is stored in /usr/local/fworch/etc/ui_admin_pwd

**Comment by alf-cactus** [comment]
@kamranrafiq may I ask how FWO caught your attention?

**Comment by kamranrafiq** [comment]
@alf-cactus I am looking for an firewall orchestrator to manage network firewalls and perform rule audits and reviews and FWO came during my search.

**Comment by kamranrafiq** [comment]
I was able to find the UI creds under: /usr/local/fworch/etc/secrets/ui_admin_pwd

Thanks!

**Comment by alf-cactus** [comment]
I am sorry, I forgot the .../secrets directory
