### ISSUE TITLE
UI - uiuser config sometimes not set properly

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1883]
- no username displayed in horizontal main nav bar
- might be connected to settings - users - sync to ldap: after executing this, the issue goes away
- JWT refresh leads to "Username must not be empty" error

**Comment by Y4nnikH** [comment]
When logging out as some user and logging in as admin next, the before logged in username will be displayed in the nav bar.

**Comment by tpurschke** [comment]
duplicate to #1853
