### ISSUE TITLE
add group search option for arbitrary ldap

### ISSUE THREAD

**Issue by abarz722** [CactuseSecurity/firewall-orchestrator#1995]

**Comment by tpurschke** [comment]
could not find any groups in cactus sample AD using pattern "*"

maybe we should use https://woshub.com/searching-ad-groups-users-using-wildcards/:

If you only want to search for AD group objects, use the following LDAP query.

```(&(objectcategory=group)(name=*sql*))

**Comment by tpurschke** [comment]
tested successfully (forgot to enter group search path in the first test)
