### ISSUE TITLE
install hangs at csharp tests 

### ISSUE THREAD

**Issue by abarz722** [CactuseSecurity/firewall-orchestrator#2114]
install (upgrade) hangs at [test : csharp tests] (for at least ~1h when aborted) if LockTest:LogLockUi() is active (even when everything but first ExecuteFileAction statement is commented out).

**Comment by tpurschke** [comment]
can you try to run 
    sudo rm -rf /var/fworch/lock 
before upgrading?

**Comment by abarz722** [comment]
> 

then it works :-)
