### ISSUE TITLE
Reporting Archive - do not show unauthorized reports

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2167]
A standard reporter is able to see reports generated by admin - also sees the download button but gets an error when clicking on it

**Comment by tpurschke** [comment]
re-tested with clean 6.4.10 install:
- created sample report as admin and saved it to archive
- created user with only reporter role and tenant tenant1_demo
- logged in with this user
This user can see the report generated by admin (but cannot download it)

**Comment by NilsPur** [comment]
@abarz722 The reason for this is the custom select check on the tables (hasura) e. g. "report_template" for the roles reporter-viewall and fw-admin. If the user is able so see the template, he is also able to see with this template generated schedules.

![grafik](https://github.com/CactuseSecurity/firewall-orchestrator/assets/48684538/4cef0f02-4d4d-4193-9281-628af3aad310)

**Comment by tpurschke** [comment]
tested again with 6.4.12:
- error reproducible using installed UI on virtual machine
- error does not exist when running UI locally debugging in vscode
