### ISSUE TITLE
UI Blazor table - filtering does not display correctly

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2181]
- when trying to filter tickets e.g. by fitle or requester, the filter pop-up is not fully displayed and therefore cannot be applied
- when filtering in Connection Report, I can define a filter for e.g. Application but the Apply button is not displayed once the filter has been set. This is mandatory for installations with a load of common service connections
- from https://github.com/IvanJosipovic/BlazorTable: This repository has been archived by the owner on Jul 10, 2024. It is now read-only. --> Integrate BlazorTable or develop new fork

**Comment by abarz722** [comment]
looks like a general problem of BlazorTable: Only the space used by the displayed items is overwritten by the filter pop-up.
We have the same behavior in all tables: settings, monitoring, archive..., but we only see it, when there are less than ~3 items displayed

**Comment by tpurschke** [comment]
Let's leave this for now until we decide on  FluentUI deployment.

**Comment by tpurschke** [comment]
@NilsPur can you please have a look at this general blazor table (css?) issue?

**Comment by SolidProgramming** [comment]
Fixed the hidden popups. But there is another issue with popsup appearing on weird locations. that's maybe because blazor table works with fixed height and width location but that's another issue.
