### ISSUE TITLE
UI Re-Login: Logout not always working?

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2234]
Can the lost connection be be caught at all?
Could we do an automatic redirect or even tab close in case the connection is completely lost?

![Screenshot from 2023-08-31 09-52-19](https://github.com/CactuseSecurity/firewall-orchestrator/assets/19877770/42526173-2058-448c-aa3e-d6c8310009fe)

**Comment by NilsPur** [comment]
Could not be reproduced as now. @tpurschke coud the apache reverse proxy be responsible?
