### ISSUE TITLE
Exception starting UI

### ISSUE THREAD

**Issue by abarz722** [CactuseSecurity/firewall-orchestrator#2243]
Launching UI in my debug environment leads to exception since PR #2229 at

builder.WebHost.UseStaticWebAssets();

Exception has occurred: CLR/System.NotSupportedException
An unhandled exception of type 'System.NotSupportedException' occurred in Microsoft.AspNetCore.dll: 'The web root changed from "C:\Users\achim\OneDrive\Dokumente\FWOrch\firewall-orchestrator-1\roles\ui\files\FWO.UI\wwwroot" to "C:\Users\achim\OneDrive\Dokumente\FWOrch\firewall-orchestrator-1\roles\ui\files\FWO.UI\". Changing the host configuration using WebApplicationBuilder.WebHost is not supported. Use WebApplication.CreateBuilder(WebApplicationOptions) instead.'
   at Microsoft.AspNetCore.Builder.ConfigureWebHostBuilder.ConfigureAppConfiguration(Action`2 configureDelegate)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.UseStaticWebAssets(IWebHostBuilder builder)
   at Program.<Main>$(String[] args) in C:\Users\achim\OneDrive\Dokumente\FWOrch\firewall-orchestrator-1\roles\ui\files\FWO.UI\Program.cs:line 20

(After commenting out this line everything works fine on the first look)

Do I need to install a new package or change something in the configuration?

**Comment by NilsPur** [comment]
Could you please try
builder.WebHost.UseWebRoot("wwwroot").UseStaticWebAssets();
instead of
builder.WebHost.UseStaticWebAssets();
seems to be a bug [in the current version of aspnetcore](https://github.com/dotnet/aspnetcore/issues/38212)

**Comment by abarz722** [comment]
Ok, that works! Thx
