### ISSUE TITLE
UI enhancements - Rule report and included links to objects

### ISSUE THREAD

**Issue by rh-cactus-github** [CactuseSecurity/firewall-orchestrator#2261]
in the rule report view links are included for the objects (networks / hosts / services) shown in the report. But clicking on those links leads to no action. It seems they only work if a certain (not obvious) precondition is met.

If the links are clicked the corresponding object in the objects pane should be shown immediately without the need to previously open the obejcts list. This is the beaviour someone expects when using a link.

- [ ] #2263

**Comment by tpurschke** [comment]
see also #972
