### ISSUE TITLE
In recertification page - object links lead to error

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2263]
problem: how to distinguish between recert reporting and recertification page?
Need to get Session Info / current page in roles/lib/files/FWO.Report/Display/RuleDisplayHtml.cs somehow

**Comment by tpurschke** [comment]
@NilsPur any idea?

**Comment by NilsPur** [comment]
Should be solvable using the relative uri: https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-7.0
