### ISSUE TITLE
Installer customizable config (settings)

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2275]
add possibility to call an external (python) script to set some customer specific config settings via API

read credentials from secrets dir for config changes (does not work for initial install)?

Alternatives:
- Add option to execute arbitrary graphql query (or sql code?)
- Could also realized via ansible -e parameters or via standard upgrade scripting (ansible)
- simply call python script once with entering user & pwd interactively which sets the following values via API:
  - text substitutions
  - modelling global services
  - modelling global areas available for modelling for everyone
  - ...

**Comment by alf-cactus** [comment]
Idea: Once new custom role/dir is created we expect custom script there. Script is executed late in ansible, maybe role cleanup and only on distributed server api or backend. Output of script creates idempotent dir and config file /etc/custom/custom.config or something like that
