### ISSUE TITLE
UI - make bootstrap css upgradable

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2291]
Radio buttons are not included in our old bootstrap 4.x version

Testing with latest bootstrap (5.3) showed the following issues which need to be fixed (these settings should all be done in site.css):

##### Questions

- [x] why do we have the following line in roles/ui/files/FWO.UI/Pages/_Host.cshtml? (no idea, deleted)

    <link href="FWO.Ui.styles.css" rel="stylesheet" />

##### General stuff
- [x] center login page
- [x] horizontal nav bar: black to blue (or we might leave it as is)
- [x] horizontal nav bar: 3 rightmost menu items should be right-aligned
- [x] Drop-down component: Re-add arrows up/down to the right
- [x] Help Pages - LSB black on black = invisible!
- [x] blazor table: when re-adding hidden columns, the popup is lacking padding at the top

##### all collapsibles (LSB, RSB, template, ...): 
- [x] collapse button fixed width (40px?)  - use rest for the name
- [x] All load and edit buttons: change color (lighter green and orange instead of yellow)

##### All pop-ups: 
- [x] centered and only 60% width
- [x] should start below horizontal nav bar (add padding?)
- [x] Header must be displayed (here: Export Report Download was missing)
- [x] background: solid white  and must include footer buttons
- [x] top right corner cancel X looks windows retro

##### Reporting
- [x] Display Rulebase scroll-bar
- [x] remove extra + at top of rule table
- [x] scrollbar within inner div (rule table) and add RSB scrollbar
- [x] add 3d-effect for header rules
- [x] table header darker
- [x] Archive: Download button - dark blue instead of light blue
- [x] Filterline Placeholder contains horizontal line!?
- [x] scheduling - active check box has become input field?!

##### NeMo
- [x] shorten all buttons to text size
- [x] edit connection - all fields need to be 5px further to the right
- [x] edit connection - LSB not readable - change colors
- [x] connection details - remove line breaks
- [x] revive background color for interfaces (getTableRowClass): all interfaces should have a darker background than normal connections

##### Tenant Settings

- [x] edit tenant - tenant ip addresses need to be 5px further to the right

##### Workflow

- [x] background for input too dark

##### Compliance

- [x] Matrix - Source missing padding
- [x] #2313

**Comment by SolidProgramming** [comment]
@tpurschke Closing as this is merged
