### ISSUE TITLE
modelling - db storage of networks inconsistent

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2380]
In modelling networks are stored with ip = ip_end = CIDR string (e.g. 10.0.0.0/8).
Everywhere else we store networks with ip = first ip of network, ip_end = last ip of network.

Could we harmonise this?

**Comment by tpurschke** [comment]
Double check If this is really still the case

**Comment by SolidProgramming** [comment]
The DB still contains wrong CIDR data...

   ----+----------+----------------+-------------------+-------------------+------+-------------+---------+----------------------+------------+-------------
  1 |        1 |                | 10.222.0.0/32     | 10.222.0.31/32    |      |             |         | manual               | f          |
  2 |        2 |                | 10.222.0.32/32    | 10.222.0.63/32    |      |             |         | manual               | f          |
  3 |        1 |                | 10.0.0.0/32       | 10.0.0.31/32      |      |             |         | manual               | f          |
  4 |        2 |                | 10.0.0.32/32      | 10.0.0.63/32      |      |             |         | manual               | f          |
  5 |          | Netz1          | 10.123.221.0/24   | 10.123.221.0/24   |      |             |      11 | importAreaSubnetData | f          |
  6 |          |                | 10.123.222.0/27   | 10.123.222.0/27   |      |             |      11 | importAreaSubnetData | f          |
  7 |          | Netz           | 10.123.222.32/27  | 10.123.222.32/27  |      |             |      11 | importAreaSubnetData | f          |
  8 |          | Test01         | 10.123.222.64/27  | 10.123.222.64/27  |      |             |      11 | importAreaSubnetData | f          |
  9 |          | Netz1          | 10.123.222.96/27  | 10.123.222.96/27  |      |             |      11 | importAreaSubnetData | f          |
 10 |          | Netz01         | 10.123.222.128/27 | 10.123.222.128/27 |      |             |      11 | importAreaSubnetData | f          |
 11 |          | Netz5          | 10.121.254.128/27 | 10.121.254.128/27 |      |             |      11 | importAreaSubnetData | f          |
 12 |          | Netz1          | 10.121.254.192/27 | 10.121.254.192/27 |      |             |      11 | importAreaSubnetData | f          |
 13 |          | Netz1          | 10.129.254.224/27 | 10.129.254.224/27 |      |             |      11 | importAreaSubnetData | f          |
 14 |          | Console        | 10.122.28.0/23    | 10.122.28.0/23    |      |             |      11 | importAreaSubnetData | f          |
 15 |          | all172         | 172.0.0.0/7       | 172.0.0.0/7       |      |             |      11 | importAreaSubnetData | f          |
 16 |          | all10          | 10.0.0.0/7        | 10.0.0.0/7        |      |             |      11 | importAreaSubnetData | f          |
 17 |        2 | NAT_APP_SERVER | 1.1.1.1/32        | 1.1.1.1/32        |      |             |      10 | manual               | f          |           1
 18 |        2 | 1234           | 1.2.3.4/32        | 1.2.3.4/32        |      |             |      10 | manual               | f          |           1

**Comment by tpurschke** [comment]
will be fixed in v9.0 (by @tpurschke )

**Comment by tpurschke** [comment]
fixed
