### ISSUE TITLE
bug: UI compliance/zones/configuration shows only 10 zones

### ISSUE THREAD

**Issue by alf-cactus** [CactuseSecurity/firewall-orchestrator#2513]
**Describe the bug**
Only 10 zones are visible, even though more are available in the system

**To Reproduce**
1. Go to compliance/zones/configuration
2. Add more than 10 zones and some will not be shown

**Expected behavior**
A scroll bar or paging would be appreciated

**Comment by tpurschke** [comment]
also for monitoring the pagination seems to be missing now
