### ISSUE TITLE
UI Rules reporting - check why CSV export is currently not possible 

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2526]
maybe simply try to re-activate this. I think we had this working before.
CSV export format should actually only be disabled for some report types (changes, ...).

**Comment by tpurschke** [comment]
this could be a good starting point for digging into the reporting side of things

**Comment by SolidProgramming** [comment]
There is currently running a check if the report type is one of the following:

-  ResolvedRules
-  ReportType.ResolvedRulesTech
-  ResolvedChanges
-  ResolvedChangesTech

If it's none of these it's automatically blocked for csv reports....

**Comment by tpurschke** [comment]
works as designed ...
