### ISSUE TITLE
UI modelling - add feedback for forbidden NA placement

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2529]
@SolidProgramming  - this can be seen when configuring "Common Network Areas" in settings - modelling.
Currently there is no feedback at all.

- [x]  also change value of txt message E9015 from "Interface cannot replace requested one: Wrong type." to "Interface cannot replace requested one: the directions of the interfaces do not match (one is a source interface, the other a destination interface)."
- [x] Add visual indicator for the user with above message

**Comment by tpurschke** [comment]
I will show you the current (lack of) functionality

**Comment by SolidProgramming** [comment]
- [ ] Add notification alert if network object is not configured for destination

**Comment by tpurschke** [comment]
completed
