### ISSUE TITLE
App-Rule-Report - duplicate objects are displayed

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2530]
- tested on various firewalls - duplicate NA objects for APP-4515: 
  -  only rules are affected with matching (red) objects are affected (but not all rules/red objects)
  -  none of the blue ones
  -  can be seen in source and destination
  -  sometimes 3 or even four identical objects are displayed
  -  services also not affected
  -  all duplicate objects have the same obj_id
  - duplicate objects appear only during last phase of rendering (filtering in UI)
  - no issues for e.g. APP-5630, COM-1611 (but for other rulebase (service-ext) COM-1611 also shows duplicates

**Comment by SolidProgramming** [comment]
@tpurschke  @abarz722 can we close this issue? This issue got solved with this PR #2532
