### ISSUE TITLE
Merge open PR C# bumps 

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2534]
- first test everything in develop (https://github.com/CactuseSecurity/firewall-orchestrator/pull/2519 is for main somehow)
- test login after the identity related PRs

**Comment by tpurschke** [comment]
@SolidProgramming can you have a look at this?

**Comment by SolidProgramming** [comment]
@tpurschke can this be closed? If im not mistaken, i bumped all packages to the new versions and you already merged the PR.

**Comment by tpurschke** [comment]
yes, this can be closed but we already have bumps PRs.
