### ISSUE TITLE
Develop - Reporting main structure broken

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2535]
The latest develop branch (v8.3.2) has the following issues :
- middle div does not adjust to device expansion
- when scrolling in report, the top floating buttons disappear at some stage

**Comment by SolidProgramming** [comment]
I'll have a look at it.

**Comment by SolidProgramming** [comment]
Maybe i need to adjust some changes from #2181

**Comment by tpurschke** [comment]
might actually not have been related to vheight=75 class as the error did not show after testing the previous PR #2538
