### ISSUE TITLE
UI Reporting Changes - Horizontal Nav bar scrolls up

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2559]
When generating long changes reports, and scrolling down, the horizontal nav bar starts scrolling up at a certain point.

![image](https://github.com/user-attachments/assets/15330586-044a-4069-b621-a88f20509d5c)

![image](https://github.com/user-attachments/assets/d3a7dae5-b7cc-4b54-b553-01511af84262)

Seems to be connected to the fixation of the device table header.

**Comment by SolidProgramming** [comment]
@tpurschke  Ah yeah in the changes report component is also a vheight75 which i already removed for rules report.

**Comment by SolidProgramming** [comment]
@tpurschke I'm closing this as it's merged...
