### ISSUE TITLE
Check Point Importer - rulebases for VSX instances not discovered

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2569]
When dealing with virtual gateways (VSX ) the current discovery functionality only discovers the "root" policy not the separate policies for each VSX.

**Comment by alf-cactus** [comment]
Could you please debug the checkpoint api call show-gateways-and-servers with details-level: full

We do this in /roles/lib/files/FWO.DeviceAutoDiscovery/CheckPointAPI.cs GetGateways

We expect result['objects'][x]['type'] in ["CpmiVsxClusterNetobj", "CpmiVsxNetobj"] when VSX is used in environment

You could search for 

"type": "CpmiVsxClusterNetobj"

and

"type": "CpmiVsxNetobj"

in your debug file

**Comment by tpurschke** [comment]
@alf-cactus 
sent you the requested output per mail

**Comment by alf-cactus** [comment]
Is the discovery working again?

**Comment by tpurschke** [comment]
can only be tested on Wed (after customer's change we had to postpone)

**Comment by tpurschke** [comment]
tested on VSX system - now works as designed.
