### ISSUE TITLE
FWREZNETZ-613 - Add CSV-Import interface for app server IP addresses in UI

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2582]
When modelling as admin role user, the menu "app server" should be enhanced so that the admin can also upload and import CSV files of the following format;

- External App-ID
- App Server Type
- App-IP-Address-Range (Start-IP+ optional End-IP) 

- [x] Add csv format to help file/icon tooltip
- [x] Display subnet  or ip range at App Server table in app server ui
- [x] Display UI message on successfull import

Duplicate IP addresses (that already exist for the application) should be ignored.

**Comment by SolidProgramming** [comment]
[appserver.csv](https://github.com/user-attachments/files/17373083/appserver.csv)
Testfile

**Comment by SolidProgramming** [comment]
[appserver.csv](https://github.com/user-attachments/files/17413208/appserver.csv)
App Server import testdata with ipv6
