### ISSUE TITLE
FWREZNETZ-387 - Request application zone creation

### ISSUE THREAD

**Issue by SolidProgramming** [CactuseSecurity/firewall-orchestrator#2597]
An application zone (AZ) group AZ<APP-ID> containing all app servers should be predefined for each application.

- naming convention for app zones: AZ05630: if the application name starts with COM, then the first digit is a 1, if it starts with APP, it is a 0; the rest of the digits is the app ID (copy this from  app role naming)  
- This object should be created on each FW-Mgr (handle this exactly  like the requesting of  the standard AR groups)
- the AZ group does only show in FWO when requesting firewall changes (in the analysis pop-up) --> tbd if we should suppress it even here
- no need for groups at area level - so we just create one AZ group per app

**Changes to settings/modelling**
- [x] turn creation of app zones on/off 
- [x] make the syntax (AZ) configurable as application zone prefix (similar to area prefix)

**Comment by tpurschke** [comment]
@SolidProgramming you could already start with the UI settings side here (including the default config values, ...)
