### ISSUE TITLE
Welcome Page has too much sanitization

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2600]
it should either 
1. be possible to add simple html tags (<br>, &uuml;) or
2. display the full text as is (with link breaks, etc.)

If 2. can be done safely (maybe by just suppressing script execution) this is preferable.

**Comment by SolidProgramming** [comment]
@tpurschke for number 2: https://github.com/mganss/HtmlSanitizer ?
The [online demo](https://xss.ganss.org/) shows exactly what you want. it removes XSS but keeps everything else

**Comment by SolidProgramming** [comment]
This should work better now. The the new string extension method creates a regex pattern that replaces all html tags except the onces in the "AllowedTags" array. Currently allowed are:  \<b>, \<br>, \<hr>

**Comment by tpurschke** [comment]
resolved
