### ISSUE TITLE
After upgrade the modelling import settings get lost

### ISSUE THREAD

**Issue by SolidProgramming** [CactuseSecurity/firewall-orchestrator#2623]
Probably due to the data type change of a config value (string to list) the loading of config values on modelling settings page failed with an error.

When saving  the (incomplete) list of config values, we lost some values which could be restored from daily db dump.

**Comment by tpurschke** [comment]
@abarz722 @SolidProgramming 
closing this as this as it will only cause issues when upgrading to 8.4.1 in installations with modelling module in use
the question is more how to avoid this in future changes on settings site.
lesson learnt: errors while entering settings pages could lead to loss of config values when saving the config.
