### ISSUE TITLE
Modelling - add app server network manually

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2629]
tested with latest dev version v8.4.2 on 2024-11-04
Reproduce by adding a network (e.g. 1.2.3.0/24) in the dialog.

It seems adding works but editing does not!?

- [x] When adding app server networks via UI dialog we get an error "Check constraint violation. new row for relation "owner_network" violates check constraint "owner_network_ip_end_is_host" - even though the values end up in the db correctly as ranges?! 
- [x] When editing the network again, only the first IP is displayed (with /32) - it should actually be displayed as a network again - converting range 1.2.3.0-1.2.3.255 back to 1.2.3.0/24 for displaying.
- [x] Looks like ranges (or networks for that matter) are also not detected as belonging to an area - add unit test for this? 

might already be fixed in develop? need to re-check this!

**Comment by tpurschke** [comment]
@SolidProgramming can this issue be closed completely?

**Comment by SolidProgramming** [comment]
> @SolidProgramming can this issue be closed completely?

yes.
