### ISSUE TITLE
GUI Fetch Users Error

### ISSUE THREAD

**Issue by alf-cactus** [CactuseSecurity/firewall-orchestrator#2643]
Happened to a client on v8.3. In GUI Settings Users no users are listed. The red error bar said

Fetch data - Unclassified error: : field 'active' not found in type 'ldap_connection_bool_exp'. See log for details!

A F5 refresh solved the problem, no more information are given

**Comment by tpurschke** [comment]
could not reproduce with v8.4.3

**Comment by tpurschke** [comment]
@alf-cactus can you try to reproduce this again?
