### ISSUE TITLE
Bug: GUI connect LDAP DN

### ISSUE THREAD

**Issue by alf-cactus** [CactuseSecurity/firewall-orchestrator#2645]
In GUI Settings LDAP Connections we can't escape a comma in a DN string

Problem example: "CN=Hofmaier\\, Valentin,DC=example,DC=com"

**Comment by tpurschke** [comment]
can you please add the desired syntax as an example as well?

**Comment by alf-cactus** [comment]
Sorry Github escaped my backslash. We want to type in GUI
"CN=Hofmaier\\, Valentin,DC=example,DC=com"
Sanitizing does not allow this
