### ISSUE TITLE
Report Export - Spinner text "Exporting"?

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2725]
Why do we have a text instead of the graphical spinner here?
Can this be fixed by using the same component everywhere?

**Comment by SolidProgramming** [comment]
> Why do we have a text instead of the graphical spinner here? Can this be fixed by using the same component everywhere?

1. The text element in the spinner doesn't has `visually-hidden` class
2. Yes

Also: Found 3 more occurences and fixed them.
