### ISSUE TITLE
UI: Reporting - BlazorTables - Fix filtering

### ISSUE THREAD

**Issue by NilsPur** [CactuseSecurity/firewall-orchestrator#341]
need to add new feature to BlazorTables in order to allow for functions other than properties to be used
- [ ] column fields need to be correctly filled (as displayed) when using Templates
- [ ] define functions to avoid code duplication

@NilsPur  - just hide filtering option for now and tackle this issue in phase 2? Yes

**Comment by tpurschke** [comment]
see #1044
