### ISSUE TITLE
UI: Customize Connection State and Messages

### ISSUE THREAD

**Issue by NilsPur** [CactuseSecurity/firewall-orchestrator#425]
- [see Connection State](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-3.1#reflect-the-connection-state-in-the-ui)
- [see Error Message](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-5.0)

~~https://stackoverflow.com/questions/58199849/how-to-detect-that-a-client-closed-the-browser-on-blazor-server-side-web-socket (useful for issue #439 and therefor copied to it)~~

**Comment by tpurschke** [comment]
@NilsPur please rename so that the goal of the issue is visible

**Comment by NilsPur** [comment]
Error messages include reference to github issue as well as email reporting.
Default connection state values are fine for now. Adaption on demand seems to be the way to go.
