### ISSUE TITLE
UI - Recertification changes (modularization)

### ISSUE THREAD

**Issue by NilsPur** [CactuseSecurity/firewall-orchestrator#984]
- [x] Create certification page
- [x] Modify current report cmponent to fit for both reporting and recertification
- [x] Add recertification specific columns (last recertification date, next recertification date, last recertificator)
- [x] Add action column (recertify, decertify, none)
- [ ] Add menu (html sticky) on top of page 
  (filter rules that need to be certified in the next x days, load rules matched by filter, execute selected actions)

**Comment by tpurschke** [comment]
resolved - moving issue with fixated menu to separate issue
